dist: xenial
sudo: false
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install: travis_retry composer update --prefer-dist

script:
  - vendor/bin/phpunit

stages:
  - Validate against schema
  - Test
  - Apply fixes

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Validate against schema
      addons:
        apt:
          packages:
            - libxml2-utils
      script:
        - xmllint --noout --schema vendor/squizlabs/php_codesniffer/phpcs.xsd lib/Doctrine/ruleset.xml
    - stage: Coding Style
      script:
        - vendor/bin/phpcs
